In [2]:
import numpy as np
import numpy.matlib

# Example confusion matrix average for 3 classes
avg_cfmat = np.array([
    [5, 1, 0],
    [2, 6, 1],
    [0, 3, 7]
])
num_classes = avg_cfmat.shape[0]

In [3]:
class_size_elementwise_old = np.transpose(
    np.matlib.repmat(np.sum(avg_cfmat, axis=1), num_classes, 1)
)

In [4]:
class_sums = np.sum(avg_cfmat, axis=1, keepdims=True)
class_size_elementwise_new = np.tile(class_sums, (1, num_classes))

In [5]:
print(np.allclose(class_size_elementwise_old, class_size_elementwise_new))  # Should print: True
print(class_size_elementwise_old)
print(class_size_elementwise_new)

True
[[ 6  6  6]
 [ 9  9  9]
 [10 10 10]]
[[ 6  6  6]
 [ 9  9  9]
 [10 10 10]]
